parameters:
#    recruiter_admin_panel.example.class: Recruiter\AdminPanelBundle\Example

services:
#    recruiter_admin_panel.example:
#        class: %recruiter_admin_panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
