<?php

namespace Recruiter\EmployerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerRepository extends EntityRepository
{
	public function countAll($joinDate = 0)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'count(r.id)')
			->add('from', 'RecruiterEmployerBundle:Employer r')
			->add('where', 'r.employer_created_at > :join_date')
			->setParameter('join_date', $joinDate)
		;
		
		return (int) $qb->getQuery()->getSingleScalarResult();
	}
	
	public function fetchWhereNameLike($term)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'e')
			->add('from', 'RecruiterEmployerBundle:Employer e')
			->add('where', 'e.employer_name like ?1')
			->setParameter(1, "%" . $term . "%")
			->addOrderBy('e.employer_name', 'ASC')
		;
		
		return $qb->getQuery()->getResult();
	}
	
	public function fetchNames()
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'e.employer_name')
			->add('from', 'RecruiterEmployerBundle:Employer e')
			->addOrderBy('e.employer_name', 'ASC')
		;
		
		$results = $qb->getQuery()->getResult();
		
		$rtn = array();
		
		foreach ($results as $result) {
			$rtn[] = "\"". $result["employer_name"] . "\"";
		}
		
		return $rtn;
	}
	
	public function fetchLatest($limit = 10)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'e')
			->add('from', 'RecruiterEmployerBundle:Employer e')
			->setMaxResults($limit)
			->addOrderBy('e.id', 'DESC')
		;
	
		return $qb->getQuery()->getResult();
	}
}
